apiVersion: v1
kind: Service
metadata:
  name: cactus-house-frontend
spec:
  type: LoadBalancer
  selector:
    app: cactus-house-frontend
  ports:
  - port: 3030
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cactus-house-frontend
spec:
  selector:
    matchLabels:
      app: cactus-house-frontend
  template:
    metadata:
      labels:
        app: cactus-house-frontend
    spec:
      containers:
      - name: cactus-house-frontend
        image: thimira97/cactus_house_web:latest
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 3000