name: CI/CD Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  dev-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to DOcker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" > .env.production

      - name: Build and push DOcker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: |
                ${{ secrets.DOCKERHUB_USERNAME }}/cactus_house_web:${{ env.SHORT_SHA }}
                ${{ secrets.DOCKERHUB_USERNAME }}/cactus_house_web:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest
    needs: dev-build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      working-directory: ./kubernetes
      run: |
        kubectl apply -f deployment.yaml